export const APPLICATION_STATUSES = {
  READY: "READY",
  AWAITING_STAKING: "AWAITING_STAKING",
  AWAITING_FUNDS: "AWAITING_FUNDS",
  AWAITING_GRACE_PERIOD: "AWAITING_GRACE_PERIOD",
  AWAITING_UNSTAKING: "AWAITING_UNSTAKING",
  AWAITING_FUNDS_REMOVAL: "AWAITING_FUNDS_REMOVAL",
  DECOMISSIONED: "DECOMISSIONED",
};
