export const APPLICATION_STATUSES = {
  AWAITING_STAKING: 'AWAITING_STAKING',
  AWAITING_FUNDS: 'AWAITING_FUNDS',
  AWAITING_FREETIER_FUNDS: 'AWAITING_FREETIER_FUNDS',
  AWAITING_FREETIER_STAKING: 'AWAITING_FREETIER_STAKING',
  AWAITING_GRACE_PERIOD: 'AWAITING_GRACE_PERIOD',
  AWAITING_UNSTAKING: 'AWAITING_UNSTAKING',
  AWAITING_FUNDS_REMOVAL: 'AWAITING_FUNDS_REMOVAL',
  DECOMISSIONED: 'DECOMISSIONED',
  IN_SERVICE: 'IN_SERVICE',
  READY: 'READY',
  SWAPPABLE: 'SWAPPABLE',
}
